import Head from "next/head";
import Snutt from "../../components/Service/Snutt/Snutt";
import Snuboard from "../../components/Service/Snuboard/Snuboard";
import Cover from "../../components/Home/Cover/Cover";
import styles from "./Service.module.scss";

function Service() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Waffle.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cover />
      <Snutt />
      <Snuboard />
    </div>
  );
}

export default Service;
