import Head from "next/head";
import Cover from "../components/Home/Cover/Cover";
import About from "../components/Home/About/About";
import { useInitiateScrollViewport } from "../hooks/scroll/useScroll";
import Billboard from "../components/Home/Billboard/Billboard";
import WhoAreWe from "../components/Home/WhoAreWe/WhoAreWe";
import Services from "../components/Home/ServiceSummary/ServicesSummary";
import Role from "../components/Home/Role/Role";
import Activity from "../components/Home/Activity/Activity";
import WhatWeDo from "../components/Home/WhatWeDo/WhatWeDo";
import Calendar from "../components/Home/Calendar/Calendar";
import QnA from "../components/Home/QnA/QnA";
import Ending from "../components/common/Ending/Ending";
import styles from "./Home.module.scss";

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Waffle.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cover />
      <Billboard />
      <About />
      <Services />
      <WhoAreWe />
      <Role />
      <Activity />
      <WhatWeDo />
      <Calendar />
      <QnA />
      <Ending type={"side"} />
    </div>
  );
}

export default Home;
