import type { NextPage } from "next";
import Head from "next/head";
import styles from "./Home.module.scss";
import Cover from "../components/Home/Cover/Cover";
import About from "../components/Home/About/About";
import { useInitiateScrollViewport } from "../hooks/scroll/useScroll";
import Billboard from "../components/Home/Billboard/Billboard";
import WhoAreWe from "../components/Home/WhoAreWe/WhoAreWe";

const Home: NextPage = () => {
  useInitiateScrollViewport();
  return (
    <div className={styles.container}>
      <Head>
        <title>Waffle.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cover />
      <Billboard />
      <About />
      <WhoAreWe />
    </div>
  );
};

export default Home;
