import Board from "../../components/Member/Board/Board";

function Member() {
  return (
    <div className="">
      {/*<Head>*/}
      {/*  <title>Waffle.com</title>*/}
      {/*  <meta name="description" content="Generated by create next app" />*/}
      {/*  <link rel="icon" href="/favicon.ico" />*/}
      {/*</Head>*/}
      {/*<Background />*/}
      {/*<Cover />*/}
      <Board />
    </div>
  );
}

export default Member;
